# Generated by Django 5.2 on 2025-04-23 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_periods', models.IntegerField(default=30)),
                ('historical_data', models.JSONField()),
                ('forecast_data', models.JSONField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(default='Cash Flow Forecast', max_length=100)),
                ('seasonality', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_periods', models.IntegerField(default=30)),
                ('historical_data', models.JSONField()),
                ('forecast_data', models.JSONField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(default='Demand Forecast', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_periods', models.IntegerField(default=30)),
                ('historical_data', models.JSONField()),
                ('forecast_data', models.JSONField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(default='Inventory Forecast', max_length=100)),
                ('holidays', models.JSONField(blank=True, null=True)),
                ('regressors', models.JSONField(blank=True, null=True)),
                ('future_regressors', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
