# Generated by Django 5.2 on 2025-04-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryforecast',
            name='future_regressors',
        ),
    ]
